"""criar tabelas alunos e inscricoes

Revision ID: da2d64f2bb59
Revises: 
Create Date: 2026-05-07 16:23:31.073958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2d64f2bb59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alunos_cpf'), 'alunos', ['cpf'], unique=True)
    op.create_index(op.f('ix_alunos_id'), 'alunos', ['id'], unique=False)
    op.create_table('inscricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('projeto', sa.String(length=100), nullable=False),
    sa.Column('curso', sa.String(length=255), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscricoes_id'), 'inscricoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inscricoes_id'), table_name='inscricoes')
    op.drop_table('inscricoes')
    op.drop_index(op.f('ix_alunos_id'), table_name='alunos')
    op.drop_index(op.f('ix_alunos_cpf'), table_name='alunos')
    op.drop_table('alunos')
    # ### end Alembic commands ###
